-- 코드를 입력하세요
SELECT MONTH(START_DATE) as MONTH, CAR_ID, count(CAR_ID) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY R 
WHERE(
    SELECT COUNT(*)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C 
    WHERE START_DATE >='2022-08-01'
    AND START_DATE <'2022-11-01'
    AND R.CAR_ID = C.CAR_ID
)>= 5
AND START_DATE >='2022-08-01'
AND START_DATE <'2022-11-01'
GROUP BY MONTH(START_DATE),CAR_ID
ORDER BY MONTH, CAR_ID DESC